### ISSUE TITLE
Dunder vars handled per PEP8 generates warning about imports not at top of file

### ISSUE THREAD

**Issue by spacebuoy** [PyCQA/pycodestyle#607] opened 2017-01-01 19:30 UTC
Sent here to this issue reporter by Andrey Vlasovskikh at PyCharm. 
This problem is mentioned at bottom of this ticket: https://github.com/PyCQA/pycodestyle/issues/264

```py
"""
Retrieve course and chapter titles from web
"""
__author__ = 'Gene'
import re
```

PEP8 https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names 
seems to require the above layout but PyCharm via pycodestyle as of May gives warning.

Will this be incorporated in pycodestyle?

**Comment by 5j9** [comment] 2017-01-22 09:17
Probably a duplicate of #394.

**Comment by sigmavirus24** [comment] 2017-01-26 12:17
This is a duplicate of #394. Thanks for noticing @5j9.

In the future @spacebuoy, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2017-01-26 12:17 UTC
