### ISSUE TITLE
Option --select=E901 works incorrectly if AST checking is enabled, e.g. via flake8

### ISSUE THREAD

**Issue by vdmit** [PyCQA/pycodestyle#432] opened 2015-08-26 06:48 UTC
Option `--select=E901` works incorrectly when compilation is failed in `check_ast` method.

In this case error E901 is reported, but option `--select=E901` magically suppresses it.
This could be easily reproduced using, for example, `flake8` utility (which triggers `check_ast` call).

Consider following sample file. It produces E901 error by `flake8` (by compile exception of type SyntaxError in `check_ast`):

```
def f()
    pass
```

By default, we see syntax error with code E901 (and some other pep8 errors, which are filtered quite good by `--select`):

```
test.py:1:7: E901 SyntaxError: invalid syntax
test.py:2:5: E113 unexpected indentation
```

And, if we wish to show only syntax errors via
`flake8 --select=E901 <file>`, we will see NO errors at all. This is very-very frustrating. Errors filtering is implemented in `pep8` core, so `flake8` is irrelevant here (see https://gitlab.com/pycqa/flake8/issues/86 fir details)

**Comment by sigmavirus24** [comment] 2015-09-17 13:30
So I think the problem is that pep8 doesn't realize that the `ast_checks` can generate an E901. The solution is to figure out how pep8 knows that, and add that call to the registry so when you do `--select=E901` it Just Works™.

**Comment by asottile** [comment] 2020-02-19 18:10
this has been fixed via flake8 3.x which no longer uses `pycodestyle` as the inclusion / exclusion framework

also note that the syntax error code changed to E999:

```console
$ ~/opt/venv/bin/flake8 t.py
t.py:1:7: E999 SyntaxError: invalid syntax
t.py:2:5: E113 unexpected indentation
t.py:3:1: W391 blank line at end of file
```

**Closed by asottile** 2020-02-19 18:10 UTC
