### ISSUE TITLE
"E501 line too long" warning prevents other warning in next line (E226)

### ISSUE THREAD

**Issue by hannob** [PyCQA/pycodestyle#702] opened 2017-11-03 09:47 UTC
I have experienced a weird behavior of pycodestyle and have trimmed it down to a minimal example:
```
#!/usr/bin/env python3

verylong = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
double = verylong+verylong

```

So this has two coding style violations: An overly long line and missing whitespaces around the + operator.

However if I run pycodestyle it says only:
```
codingstyleglitch:3:80: E501 line too long (115 > 79 characters)
```

The second error about the missing whitespaces is not shown. Yet when I tell pycodingstyle to ignore line too long errors with 'pycodestyle --ignore=E501 codingstyleglitch'  I get:
```
codingstyleglitch:4:18: E226 missing whitespace around arithmetic operator
```

So somehow it seems a coding style violation in one line will prevent detection of a coding style violation in the following line. I don't think that's intended.

**Comment by IanLee1521** [comment] 2017-11-03 18:11
Good catch!

I confirmed the behavior on the latest master (f810ae199e895d4274f527be1dd705fc275a2cb5). I'm not sure of an ETA to a solution, but if you're willing to look into it and submit a pull request, I can review that.

**Comment by ricardo-martincoski** [comment] 2018-02-12 03:57
I found the same behaviour and confirmed it in the latest master (01ecae5a).

Interesting: the use of --ignore makes the issue to not occur.

```
$ ./pycodestyle.py testsuite/E50.py > without.txt
$ ./pycodestyle.py --ignore=anyvalue testsuite/E50.py > with.txt
$ diff without.txt with.txt
10a11
> testsuite/E50.py:63:67: E226 missing whitespace around arithmetic operator

```

**Comment by sigmavirus24** [comment] 2018-02-12 15:53
This isn't a bug, I think:

https://github.com/PyCQA/pycodestyle/blob/01ecae5a87d2bdf7df6528722e0c2ae36930d90f/pycodestyle.py#L83

E226 appears to be in the `DEFAULT_IGNORE` which is why it doesn't present itself in tests or when specifying `--ignore`.

**Comment by ricardo-martincoski** [comment] 2018-02-12 19:46
Indeed it is not a bug! 

I can see the default list on the help (for version 2.3.1 in my case)

```
  --ignore=errors      skip errors and warnings (e.g. E4,W) (default:
                       E121,E123,E126,E226,E24,E704,W503)

```
What I want to do is to use the defaults and ignore one more error code.
I wrongly used this line on .flake8:
`ignore=E129`
but the correct use is this:
`ignore=<default list>,<extra error code to ignore>`
`ignore=E121,E123,E126,E226,E24,E704,W503,E129`

Thank you for your analysis.
Sorry for the noise.

**Comment by sigmavirus24** [comment] 2018-02-14 12:35
Right that's a separate feature request which already exists. In that case, I'll close this.

**Closed by sigmavirus24** 2018-02-14 12:35 UTC
