### ISSUE TITLE
E122 false positive after new line string concatenation with f-string

### ISSUE THREAD

**Issue by dsotirho-ucsc** [PyCQA/pycodestyle#1263] opened 2024-09-28 01:22 UTC
The following code…

```
dict(a='AAA'
       f'{4*2}',
     b=[
         'BBB',
         'BBB',
     ],
     c='CCC')
```

…causes

```
example.py:6:6: E122 continuation line missing indentation or outdented
```

The required conditions for this false positive appear to be:
- an argument who's value is a string concatenation that includes an f-string
- a following argument who's value is a multi-line list statement

The false positive does not occur if:
- `a` is only an f-string
- `a` is a new line concatenated string without an f-string
- `b` is a single line list literal
- `b` occurs before `a`

Verified with flake8 7.1.1

**Comment by asottile** [comment] 2024-09-28 01:53
fairly certain this is a duplicate of #408 and/or #372 -- that said that code is pretty ugly so not surprised there's a diagnostic from it

**Closed by asottile** 2024-09-28 01:53 UTC
