### ISSUE TITLE
E265: Positive for shebang line

### ISSUE THREAD

**Issue by felipepacci** [PyCQA/pycodestyle#963] opened 2020-10-01 00:28 UTC
I'm new to Python. I'm not sure if this issue has been resolved. I searched extensively and couldn't find a solution.

pycodestyle is currently throwing E265 at shebang lines. Is there a way to fix that behavior or disable such warning for shebang lines (`# noqa` doesn't work to disable E265 at the line level)?

**Comment by asottile** [comment] 2020-10-01 00:45
since you're new, I'll give you a few tips about bug reports (in general) that can help you in the future to get help more accurately and faster:
- include a minimal reproduction of your issue (show a source file, etc.)
- show the version information for the relevant tools you're using (many tools support `--version` or for python you can use `pip freeze` etc.)
- search the issue tracker for relevant issues (for example in this tracker I've gone through and labeled issues with the relevant code at the beginning).  github will also suggest issues as you create them (usually with reasonably high accuracy!) -- check those as well

for example, I cannot reproduce your findings on the latest version of pycodestyle:

```console
$ head -2 testing/zipapp/make 
#!/usr/bin/env python3
import argparse
$ ~/opt/venv/bin/pycodestyle testing/zipapp/make
$ ~/opt/venv/bin/pycodestyle --version
2.6.0

```

**Comment by felipepacci** [comment] 2020-10-01 01:47
> since you're new, I'll give you a few tips about bug reports (in general) that can help you in the future to get help more accurately and faster:
> 
> * include a minimal reproduction of your issue (show a source file, etc.)
> * show the version information for the relevant tools you're using (many tools support `--version` or for python you can use `pip freeze` etc.)
> * search the issue tracker for relevant issues (for example in this tracker I've gone through and labeled issues with the relevant code at the beginning).  github will also suggest issues as you create them (usually with reasonably high accuracy!) -- check those as well
> 
> for example, I cannot reproduce your findings on the latest version of pycodestyle:
> 
> ```
> $ head -2 testing/zipapp/make 
> #!/usr/bin/env python3
> import argparse
> $ ~/opt/venv/bin/pycodestyle testing/zipapp/make
> $ ~/opt/venv/bin/pycodestyle --version
> 2.6.0
> ```

Thanks for the tips, @asottile! I really appreciate them!

I'm getting this issue using Spyder 4.0.1 which I believe is using pycodestyle 2.5.0 (I checked the versions of both in the Anaconda-Navigator environment I'm launching Spyder from). I'm using these versions because the script I have to edit was written in Python 2 (the environment I'm using is running Python 2.7.18). I attach a screenshot of what I see with this message. I couldn't find anything similar using the issue tracker tool.

<img width="583" alt="Screen Shot 2020-09-30 at 8 41 59 PM" src="https://user-images.githubusercontent.com/22988001/94756752-fdcf5f80-035d-11eb-8e26-86028b093af1.png">

**Comment by asottile** [comment] 2020-10-01 02:19
those two lines are in the wrong order, the shebang *must* be the first line which makes it an exact duplicate of #757

another tip: don't post screenshots of text: they are not accessible to readers (one can't increase the font size or use a different contrast setting or use a screen reader) and they are not searchable (especially helpful for those landing from a search engine)

**Closed by asottile** 2020-10-01 02:19 UTC
