### ISSUE TITLE
pycodestyle as config section

### ISSUE THREAD

**Issue by bsipocz** [PyCQA/pycodestyle#550] opened 2016-06-21 16:16 UTC
It seems that ``pycodestyle`` is not recognizing the section in ``setup.cfg`` if it's called ``[pycodestyle]``, but it only accepts ``[pep8]``.

e.g. https://travis-ci.org/astropy/astropy/jobs/137944224#L476

**Comment by sigmavirus24** [comment] 2016-06-21 16:45
I'm looking at the pull request that you've made that triggered that job and I do not see changes to `setup.cfg`. (See: https://github.com/astropy/astropy/pull/5107/files). It also doesn't seem that the section is there on master (https://github.com/astropy/astropy/blob/352a2312ddf5b082aceb8cfa0fed4278b134313d/setup.cfg).

Looking at the logic, it should be processing `[pycodestyle]` out of the config file.

**Comment by jayvdb** [comment] 2016-06-21 16:59
@sigmavirus24 , see the first of the two commits in that series : https://github.com/astropy/astropy/pull/5107/commits , and its failing job https://travis-ci.org/astropy/astropy/jobs/137944224#L475

**Comment by sigmavirus24** [comment] 2016-06-21 18:23
Ah the problem is [here](https://github.com/PyCQA/pycodestyle/blob/fd4f1c286cdc4e0bc25822e10742adbc9062af15/pycodestyle.py#L1955). And this would be fixed by a new release of pycodestyle /cc @IanLee1521

**Closed** 2016-06-25 20:42 UTC

**Comment by tseaver** [comment] 2016-08-17 19:25
Is there an ETA for a release containing this fix?
