### ISSUE TITLE
Add check for whitespace around logical operators

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/pycodestyle#843] opened 2019-02-17 00:02 UTC
[This twitter thread](https://twitter.com/DRMacIver/status/1096080462097846278) contains a few observations, but most relevant is that `pycodestyle` does not emit any warnings or errors on the following file:

```python
0and 1
0x1or 0
```

These are legal statements and the lexer breaks the first part up appropriately, but it would be nice to have `E225 missing whitespace around operator`, or an equivalent error, apply to `and` and `or` as well as the various comparison operators.

**Comment by asottile** [comment] 2019-02-17 00:05
#631 has some other ~equivalent cases

**Comment by peterjc** [comment] 2019-05-27 13:25
This issue seems to cover the E225 false positive test cases I wanted to file:

```python
"""This is an E225 test case."""
print(3 in (1, 2, 3, 4, 5))  # True; should pass QC
print(10 in(1, 2, 3, 4, 5))  # False; should fail E225?
print(None or(1, 2))  # (1, 2); should fail E225?
```

pycodestyle 2.4.0 does not complain about these lines where I would expect it to, especially quoting http://pycodestyle.pycqa.org/en/latest/_modules/pycodestyle.html?highlight=E227 which begins:

```python
@register_check
def missing_whitespace_around_operator(logical_line, tokens):
    r"""Surround operators with a single space on either side.

    - Always surround these binary operators with a single space on
      either side: assignment (=), augmented assignment (+=, -= etc.),
      comparisons (==, <, >, !=, <=, >=, in, not in, is, is not),
      Booleans (and, or, not).

    - If operators with different priorities are used, consider adding
      whitespace around the operators with the lowest priorities.
```

Clearly says ``*Always surround these binary operators with a single space on either side: ... in, ..., or ...*" - presumably the opening bracket makes it look like a function call?

**Comment by asottile** [comment] 2020-02-19 21:23
Duplicate of #371

**Closed by asottile** 2020-02-19 21:23 UTC
