### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#742] opened 2018-04-10 16:43 UTC
@sigmavirus24 any idea why the build is failing for just python 3.5 ? 

https://travis-ci.org/PyCQA/pycodestyle/jobs/364561705

Something related to flake8, but I'm not sure what:

```
Traceback (most recent call last):
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/home/travis/build/PyCQA/pycodestyle/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.
ERROR: InvocationError for command '/home/travis/build/PyCQA/pycodestyle/.tox/flake8/bin/flake8 pycodestyle.py' (exited with code 1)
```

**Comment by sigmavirus24** [comment] 2018-04-10 18:58
Duplicate of #741

**Closed by sigmavirus24** 2018-04-10 18:58 UTC
