### ISSUE TITLE
config file is not used

### ISSUE THREAD

**Issue by keradus** [PyCQA/pycodestyle#564] opened 2016-07-26 10:56 UTC
Hi!

I wanna switch to 2.0.0 version and I have some problems with it.

```
bin/pycodestyle --version
2.0.0
```

used config (from: https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration)
```
vagrant@foo:/bar$ cat setup.cfg 
[pycodestyle]
max_line_length = 180
```
is not working.

when i change it into 
```
vagrant@foo:/bar$ cat setup.cfg 
[pep8]
max_line_length = 180
```
it works.

why i need to use old name and not new one, as stated in docs ?

**Comment by sigmavirus24** [comment] 2016-07-26 11:29
This is a duplicate of https://github.com/PyCQA/pycodestyle/issues/563 and https://github.com/PyCQA/pycodestyle/issues/550. Please check open **and** closed issues before filing new ones.

**Closed by sigmavirus24** 2016-07-26 11:29 UTC

**Comment by keradus** [comment] 2016-07-26 11:45
as the bug is still not fixed on stable version I looked only on opened tickets.

any ETA about releasing the fix?

**Comment by sigmavirus24** [comment] 2016-07-26 12:00
> as the bug is still not fixed on stable version I looked only on opened tickets.

Like most projects. Bugs are closed as they are fixed.

> any ETA about releasing the fix?

I have none. @IanLee1521 performs releases. If he wants me to get 2.1.0 ready, though, I can.

**Comment by keradus** [comment] 2016-07-26 12:26
Most projects keep the docs published for last stable release, not for next, not yet released ;)

Bugfix could go to PATCH version, so 2.0.1, if you don't want to create bigger release now.

One way or another thanks for guiding, I do appreciate it !

**Comment by sigmavirus24** [comment] 2016-07-26 12:27
> Bugfix could go to PATCH version, so 2.0.1, if you don't want to create bigger release now.

Except that the next planned release is 2.1.0, although I don't suppose @IanLee1521 documents that anywhere.
