### ISSUE TITLE
Support for max line length for string and comment

### ISSUE THREAD

**Issue by blueyed** [PyCQA/pycodestyle#681] opened 2017-09-13 10:31 UTC
I've found that luacheck has support for different types of max-line-length:

> * New `--[no-]max-code-line-length`, `--[no-]max-string-line-length`,
  `--[no-]max-comment-line-length` CLI options and corresponding
  config and inline options that limit line length only for subsets of lines
  based on line type: string lines have their line endings within a string,
  comment lines have their line endings within a comment, other lines
  are code lines

It would be nice if this was supported by pycodestyle in a similar way:

Given a max line length of 79, you often have to wrap long strings or comments (or append a `#  noqa` comment), which might result in e.g. an error message not being easily greppable.

It would be nice to have e.g. new options `max-string-line-length` and `max-comment-line-length` that would be applied for when the line ends with a string or comment, falling back to `max-line-length`.

**Comment by asottile** [comment] 2020-02-19 21:33
Duplicate of #906 (which has ~slightly more context)

**Closed by asottile** 2020-02-19 21:33 UTC
