### ISSUE TITLE
crash when concatenating multiple strings containing newlines without trailing newline at EoF

### ISSUE THREAD

**Issue by jonny-qmenta** [PyCQA/pycodestyle#727] opened 2018-02-05 14:19 UTC
**Given**:
```
def func(variable):
    return """
""" + variable + """
"""
```
_without a trailing newline at EoF_.

**When I run**:
pycodestyle file.py
with either python2.7 (pep8 v1.7.1) or python3.5 (pycodestyle v2.3.1)

**Then I get** (quoted from python3.5, but same result in python2.7):
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 2327, in <module>
>     _main()
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 2309, in _main
>     report = style_guide.check_files()
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 2010, in check_files
>     runner(path)
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 2022, in input_file
>     return fchecker.check_all(expected=expected, line_offset=line_offset)
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 1785, in check_all
>     self.check_logical()
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 1663, in check_logical
>     for offset, text in self.run_check(check, argument_names) or ():
>   File ".../env3/lib/python3.5/site-packages/pycodestyle.py", line 633, in continued_indentation
>     rel_indent[end[0] - first_row] = rel_indent[row]
> IndexError: list assignment index out of range

**Expected**:
A warning about a missing newline at EoF.

**See also**:
https://github.com/PyCQA/pycodestyle/issues/713
That appears to be related, but there are no escaped newlines here - only quoted newlines.

**Comment by asottile** [comment] 2020-02-19 21:07
Duplicate of #713

**Closed by asottile** 2020-02-19 21:07 UTC
