### ISSUE TITLE
--max-doc-length option is not working

### ISSUE THREAD

**Issue by keisen** [PyCQA/pycodestyle#1001] opened 2021-07-01 11:11 UTC
I'm currently facing the problem that it looks `max-doc-length` option is NOT working.
I've submitted the code to reproduce the problem, please see the notebook below for details.

https://gist.github.com/keisen/3cc3ebb569e92b21edcfda1be22b9476#file-is-max-doc-length-option-working-ipynb

Here, just in case, I write the reproduce steps.

1. Prepare the Python file that has docstring lines whose length is up to `--max-doc-length`, and code lines whose length is up to `--max-line-length`.
2. Run `pycodestyle` command with `--max-line-length` and `--max-doc-length`
   * `E501 line too long` error occurred
3. Run `pycodestyle` command with only `--max-doc-length`
   * `E501 line too long` error occurred

Any help would be great. Thanks!

**Comment by asottile** [comment] 2021-07-01 13:48
can you show an example not using a notebook? I don't trust executing random notebooks and it might be the problem you're seeing in the first place

**Comment by keisen** [comment] 2021-07-01 14:08
```bash
#!/bin/bash

pip install -U pycodestyle

cat <<EXAMPLE >> example.py
class ExampleClass(object):
    """I want docstring to allow a length of 80.
                                                  The lenght of this line is 80.
    """
    def __init__(self):
        print("                      The length of this line is 70.")
EXAMPLE

echo "# Run pycodestyle --max-line-length=70 --max-doc-length=80 example.py"

pycodestyle --ignore=W292 \
    --max-line-length=70 \
    --max-doc-length=80 \
    example.py

echo "# Run pycodestyle --max-line-length=70 example.py"

pycodestyle --ignore=W292 \
    --max-line-length=70 \
    example.py
```

Hi @asottile , Is this okay?

**Comment by keisen** [comment] 2021-07-01 14:11
I forgot the result of the script.

```
# Run pycodestyle --max-line-length=70 --max-doc-length=80 example.py
example.py:3:71: E501 line too long (80 > 70 characters)
# Run pycodestyle --max-line-length=70 example.py
example.py:3:71: E501 line too long (80 > 70 characters)
```

**Comment by asottile** [comment] 2021-07-01 14:24
the output makes sense to me, max-doc-length is intended to be more restrictive than max-line-length (the example in pep8 iirc is 80 and 74)

**Comment by keisen** [comment] 2021-07-01 15:51
Thank you for your quick response!

I understand what you mean. However, because our docstring has a lot of long web URL links, I want to avoid to include frequent line breaks in the docstring. So could you please consider to allow larger max-doc-length than max-line-length, or addition of option to turn checking length of docstring on/off ?

Thanks!

**Comment by asottile** [comment] 2021-07-01 16:10
urls are already excluded from line length checks

closing since this is already working as intended

**Closed by asottile** 2021-07-01 16:10 UTC
