### ISSUE TITLE
E101: checker misreports issue with triple-quote literal after `# noqa: E101` is specified on the "right block"

### ISSUE THREAD

**Issue by ngie-eign** [PyCQA/pycodestyle#886] opened 2019-09-24 20:22 UTC
My group wrote a C code generator in python once upon a time, which has some embedded C in in. Because the style used by the group mismatches with PEP8 for the content, flake8 warns about some stylistic issues with the embedded template code.

Applying `#noqa: E101,E122` works around the issue, except it still misreports one of the lines:
```
$ flake8 --version
3.7.7 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.4 on Linux
$ flake8 ~/flake8_bug.py 
/home/ecooper/flake8_bug.py:20:1: E101 indentation contains mixed spaces and tabs
$ hexdump -C ~/flake8_bug.py 
00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 65 6e 76 20 70  |#!/usr/bin/env p|
00000010  79 74 68 6f 6e 0a 0a 66  72 6f 6d 20 5f 5f 66 75  |ython..from __fu|
00000020  74 75 72 65 5f 5f 20 69  6d 70 6f 72 74 20 70 72  |ture__ import pr|
00000030  69 6e 74 5f 66 75 6e 63  74 69 6f 6e 0a 0a 0a 64  |int_function...d|
00000040  65 66 20 68 65 6c 6c 6f  5f 77 6f 72 6c 64 28 29  |ef hello_world()|
00000050  3a 0a 20 20 20 20 73 20  3d 20 5c 0a 22 22 22 2f  |:.    s = \."""/|
00000060  2a 0a 2a 20 59 65 20 6f  6c 64 65 2c 20 68 65 6c  |*.* Ye olde, hel|
00000070  6c 6f 20 77 6f 72 6c 64  20 70 72 6f 67 72 61 6d  |lo world program|
00000080  20 28 69 6e 20 43 21 29  21 0a 2a 2f 0a 0a 23 69  | (in C!)!.*/..#i|
00000090  6e 63 6c 75 64 65 20 3c  73 74 64 69 6f 2e 68 3e  |nclude <stdio.h>|
000000a0  0a 0a 69 6e 74 0a 6d 61  69 6e 28 76 6f 69 64 29  |..int.main(void)|
000000b0  20 7b 0a 09 70 72 69 6e  74 66 28 22 68 65 6c 6c  | {..printf("hell|
000000c0  6f 20 77 6f 72 6c 64 21  5c 6e 22 29 3b 0a 09 72  |o world!\n");..r|
000000d0  65 74 75 72 6e 20 28 30  29 3b 0a 7d 0a 22 22 22  |eturn (0);.}."""|
000000e0  20 20 23 20 6e 6f 71 61  3a 20 45 31 30 31 2c 45  |  # noqa: E101,E|
000000f0  31 32 32 2c 57 31 39 31  0a 20 20 20 20 70 72 69  |122,W191.    pri|
00000100  6e 74 28 73 2c 20 65 6e  64 3d 22 22 29 0a 0a 0a  |nt(s, end="")...|
00000110  69 66 20 5f 5f 6e 61 6d  65 5f 5f 20 3d 3d 20 22  |if __name__ == "|
00000120  5f 5f 6d 61 69 6e 5f 5f  22 3a 0a 20 20 20 20 68  |__main__":.    h|
00000130  65 6c 6c 6f 5f 77 6f 72  6c 64 28 29 0a           |ello_world().|
0000013d
```

The issue reported on line 20 is bogus (it's a properly formatted line, which aligns with the formatting from line 7). I suspect what happened with the triple-quote string literal is that it reset `indent_char` somehow, which is wrong.

Sample file attached.

[pycodestyle_bug.py.txt](https://github.com/PyCQA/pycodestyle/files/3649271/pycodestyle_bug.py.txt)

**Comment by asottile** [comment] 2019-09-24 20:29
this appears to be a bug with `flake8` and not with `pycodestyle` -- let's continue this there:  https://gitlab.com/pycqa/flake8

```console
$ python3 -m pycodestyle t.py
$ echo $?
0
$ flake8 t.py
t.py:20:1: E101 indentation contains mixed spaces and tabs
```

**Comment by asottile** [comment] 2019-09-24 20:47
actually 🤔

if you remove the noqa it resurfaces, making this less clear cut on what the correct behaviour is here:

```console
$ python3 -m pycodestyle t.py
t.py:8:1: E122 continuation line missing indentation or outdented
t.py:16:1: E101 indentation contains mixed spaces and tabs
t.py:16:1: W191 indentation contains tabs
t.py:17:1: W191 indentation contains tabs
t.py:20:1: E101 indentation contains mixed spaces and tabs
```

**Comment by asottile** [comment] 2019-09-24 20:50
to me this patch to `pycodestyle` makes the most sense:

```diff
$ git diff
diff --git a/pycodestyle.py b/pycodestyle.py
index 4ade087..17ed575 100755
--- a/pycodestyle.py
+++ b/pycodestyle.py
@@ -1980,8 +1980,6 @@ class Checker(object):
             if result is not None:
                 (offset, text) = result
                 self.report_error(self.line_number, offset, text, check)
-                if text[:4] == 'E101':
-                    self.indent_char = line[0]
 
     def build_tokens_line(self):
         """Build a logical line from tokens."""
```

plus this patch to flake8:

```diff
$ git diff | cat
diff --git a/src/flake8/checker.py b/src/flake8/checker.py
index 2df7e42..9e1c7c8 100644
--- a/src/flake8/checker.py
+++ b/src/flake8/checker.py
@@ -565,9 +565,6 @@ class FileChecker(object):
                         text=text,
                         line=(override_error_line or physical_line),
                     )
-                    self.processor.check_physical_error(
-                        error_code, physical_line
-                    )
 
     def process_tokens(self):
         """Process tokens and trigger checks.
diff --git a/src/flake8/processor.py b/src/flake8/processor.py
index dad4d7b..83e2afc 100644
--- a/src/flake8/processor.py
+++ b/src/flake8/processor.py
@@ -261,12 +261,6 @@ class FileProcessor(object):
                     )
         return arguments
 
-    def check_physical_error(self, error_code, line):
-        # type: (str, str) -> None
-        """Update attributes based on error code and line."""
-        if error_code == "E101":
-            self.indent_char = line[0]
-
     def generate_tokens(self):  # type: () -> Generator[_Token, None, None]
         """Tokenize the file and yield the tokens.
 
diff --git a/tests/integration/test_main.py b/tests/integration/test_main.py
index 72e9621..891bafb 100644
--- a/tests/integration/test_main.py
+++ b/tests/integration/test_main.py
@@ -51,6 +51,25 @@ index d64ac39..7d943de 100644
     assert err == ''
 
 
+def test_E101_indent_char_resetting(tmpdir, capsys):
+    """Ensure that E101 with an existing indent_char does not reset it."""
+    t_py_contents = """\
+if True:
+    print('space indented')
+
+s = '''\
+\ttab indented
+'''  # noqa: E101
+
+if True:
+    print('space indented')
+"""
+
+    with tmpdir.as_cwd():
+        tmpdir.join('t.py').write(t_py_contents)
+        _call_main(['t.py'])
+
+
 def test_statistics_option(tmpdir, capsys):
     """Ensure that `flake8 --statistics` works."""
     with tmpdir.as_cwd():
diff --git a/tests/unit/test_file_processor.py b/tests/unit/test_file_processor.py
index c3ae021..afae77d 100644
--- a/tests/unit/test_file_processor.py
+++ b/tests/unit/test_file_processor.py
@@ -146,24 +146,6 @@ def test_next_line(default_options):
         assert file_processor.line_number == i
 
 
-@pytest.mark.parametrize('error_code, line, expected_indent_char', [
-    ('E101', '\t\ta = 1', '\t'),
-    ('E101', '    a = 1', ' '),
-    ('W101', 'frobulate()', None),
-    ('F821', 'class FizBuz:', None),
-])
-def test_check_physical_error(
-        error_code, line, expected_indent_char, default_options,
-):
-    """Verify we update the indet char for the appropriate error code."""
-    file_processor = processor.FileProcessor('-', default_options, lines=[
-        'Line 1',
-    ])
-
-    file_processor.check_physical_error(error_code, line)
-    assert file_processor.indent_char == expected_indent_char
-
-
 @pytest.mark.parametrize('params, args, expected_kwargs', [
     ({'blank_before': True, 'blank_lines': True},
         None,
```

**Comment by asottile** [comment] 2019-09-24 21:38
here's flake8's part of that: https://gitlab.com/pycqa/flake8/merge_requests/357

**Comment by Zac-HD** [comment] 2021-09-22 23:40
I encountered what I *think* is the same problem, and reduced it to the following case:

```python
"""
this is not indented
	this is tab-indented, and it's not code at all
"""

while True:
    pass  # this is four-space-indented
```
```shell
$ pycodestyle t.py
t.py:3:1: W191 indentation contains tabs
t.py:7:1: E101 indentation contains mixed spaces and tabs
```
which makes it look like a duplicate of #376.

**Comment by asottile** [comment] 2021-09-22 23:49
yeah I agree on duplicate -- let's coordinate there

**Closed by asottile** 2021-09-22 23:49 UTC
