### ISSUE TITLE
E721 false positives

### ISSUE THREAD

**Issue by saleemrashid** [PyCQA/pycodestyle#671] opened 2017-07-31 10:41 UTC
In https://github.com/trezor/python-trezor/pull/124, there are comparisons like `msg.type == types.PinMatrixRequestType_Current`, where `msg.type` and `types.PinMatrixRequestType_Current` are `int`.

 This gives a false positive because `COMPARE_TYPE_REGEX` does not check if `type` is a function call, and `PinMatrixRequestType_Current` contains the word `Type`.

**Comment by asottile** [comment] 2020-02-19 20:51
while #830 is a duplicate of this one, I believe that one has more information so we can continue discussion there!

**Closed by asottile** 2020-02-19 20:51 UTC
