### ISSUE TITLE
E302 expected 2 blank lines, found 0 for single multiline function definition in file

### ISSUE THREAD

**Issue by tbicr** [PyCQA/pycodestyle#860] opened 2019-03-27 21:07 UTC
python: 3.7.2
pycodestyle: 2.5.0

E302 expected 2 blank lines, found 0 for single multiline function definition in file, but no issue single line function definition

haven file:

```
def test(
    param_1234567890_1, param_1234567890_2, param_1234567890_3, param_1234567890_4
):
    pass
```

run:
`flake8 file.py`

got:
`file.py:1:1: E302 expected 2 blank lines, found 0`

expected:
no issue as for file with next content:
```
def test(param_1234567890_1, param_1234567890_2, param_1234567890_3, param_1234567890_4):
    pass
```

**Comment by asottile** [comment] 2020-02-19 21:25
Duplicate of #473

**Closed by asottile** 2020-02-19 21:25 UTC
