### ISSUE TITLE
E251 incompatible with defaults for typed attributes

### ISSUE THREAD

**Issue by ambv** [PyCQA/pycodestyle#551] opened 2016-06-23 19:01 UTC
Quoting PEP 8:

> When combining an argument annotation with a default value, use spaces around the = sign (but only for those arguments that have both an annotation and a default)

An example is given:
```
def munge(input: AnyStr, sep: AnyStr = None, limit=1000): ...
```

However, `pycodestyle` currently raises "E251 unexpected spaces around keyword / parameter equals" for this case.

**Comment by sigmavirus24** [comment] 2016-06-23 19:34
What version are you using?

**Comment by sigmavirus24** [comment] 2016-06-23 19:37
To be clear https://github.com/PyCQA/pycodestyle/issues/507 should have been fixed by #508

**Comment by sigmavirus24** [comment] 2016-06-23 21:28
Using pycodestyle 2.0.0 I can't reproduce this.

**Comment by IanLee1521** [comment] 2016-06-25 20:19
Can't repoduce in e01ca2f9de13e570d567eaad785fa78e096e34ef either, going to go ahead and close this.

**Closed by IanLee1521** 2016-06-25 20:19 UTC

**Comment by ambv** [comment] 2016-06-27 00:40
Yup, you're right. I was using pep8 1.7.0.
