### ISSUE TITLE
"E262 inline comment should start with '# '" even though inline comment does start with '# '

### ISSUE THREAD

**Issue by josch** [PyCQA/pycodestyle#403] opened 2015-05-21 12:28 UTC
to reproduce:

```
$ echo 'l = 1  #  foobar' | pep8 -
stdin:1:8: E262 inline comment should start with '# '
```

Though evidently, the inline comment does start with `#` (hash followed by a space).

Pep8 itself also does not forbid an inline comment to have two spaces before the actual text starts.

My actual use case for starting an inline comment with two spaces after the hash are a snippet like the following:

```
l = [
    "foo",  #  1
    "bar",  #  2
    ...
    "baz",  # 10
    ...
]
```

This is a minimal example which should demonstrate that allowing an inline comment with two leading spaces is useful in case one wants to right-align numbers. Having each line commented like above is useful because in case an error happens, the error will point out the element in the list from where the error originated. Since the list is several hundred elements long and its elements are not just simple strings as above, the comments make it easier to find the right element.

**Comment by porglezomp** [comment] 2015-05-23 21:55
In the example it's probably better to just pad with zeros like:
```
l = [
    "foo",  # 01
    "bar",  # 02
    ...
    "baz",  # 10
    ...
]
```

**Comment by josch** [comment] 2015-05-24 12:04
Maybe but that still leaves the problem that the comments *do* start with a hash and a space and pep8 still complains that they are not doing that...

**Comment by porglezomp** [comment] 2015-05-24 14:49
PEP 8 says (emphasis mine):

> They should start with a # and __a single space__.

Which seems to indicate that it wants one space, no more, no less.

**Comment by josch** [comment] 2015-05-24 15:13
Ah indeed. Natural language can be tricky. I read it like: "If I have five apples then it is also true that I  have a single apple". Then maybe the error message should be adapted to make it more clear how this module reads pep8. Maybe by saying: "E262 inline comment should start with '# ' followed by a non-space character".

**Comment by sigmavirus24** [comment] 2015-05-24 15:26
"followed by a single space" I think would be the best way to rewrite the error message.

**Comment by josch** [comment] 2015-05-24 15:28
That formulation would've still triggered me opening this bug because of the understanding I described in my earler post. But I'm also not a native english speaker so I'll just let you pick the best option now :)

**Comment by porglezomp** [comment] 2015-05-24 15:38
"Followed by exactly one space" perhaps? I think followed by a single space might be good enough in most cases, and sounds better, but it's still _somewhat_ ambiguous.

**Comment by sigmavirus24** [comment] 2015-05-24 15:57
"Followed by exactly one space" could be good until the document changes. Keeping the messages as close to the document (for now) is better in my opinion because it prevents wording becoming heavy-handed. It's also not clear to me that referring people to the document for these errors would be helpful, and I don't think "Followed by exactly one space" could be read unambiguously by someone for whom English is a second language.

**Comment by Glutexo** [comment] 2018-01-24 19:03
Just in case you found this for the same reason as I did: I had a non-breaking space (U+00A0) instead of a regular one. They looked the same in the editor, but Flake complained.

**Comment by asottile** [comment] 2020-02-19 18:02
closing as this appears to be working as intended (exactly one space)

**Closed by asottile** 2020-02-19 18:02 UTC
