### ISSUE TITLE
Add a rule to discourage trailing comma out of any brackets.

### ISSUE THREAD

**Issue by frostming** [PyCQA/pycodestyle#857] opened 2019-03-25 03:28 UTC
As title, warn user against following:

```python
a = 2,
```

But passes like this:
```python
a = (
    2,
)
```

**Comment by asottile** [comment] 2019-03-25 04:00
fwiw PEP8 says about this [OK, but confusing](https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas), not sure this is the right place to add such a rule given that 🤔

**Comment by FichteFoll** [comment] 2019-03-25 12:52
The variant with parens is clearly a better alternative, even if a simple trailing comma isn't forbidden per se. I wouldn't see an issue with adding a check for this, maybe optional.

**Comment by Trim21** [comment] 2019-05-19 06:09
I have an implement as pre-commit hook and I'd like to start a PR for this issue. But I'm sure if members consider this rule useful.

https://github.com/Trim21/find-trailing-comma

**Comment by Trim21** [comment] 2019-05-19 06:11
And do you think `a = 1, 2, 3,` confusing or it's cleanly a tuple and don't need a warning at all?

**Comment by asottile** [comment] 2020-02-19 21:24
duplicate of #691

**Closed by asottile** 2020-02-19 21:24 UTC
