### ISSUE TITLE
False positive E712 (comparison to False) when comparing with arrays

### ISSUE THREAD

**Issue by lzkelley** [PyCQA/pycodestyle#450] opened 2015-10-23 19:52 UTC
For an array of boolean values `valid`, if I want to find the `False` elements I might use something like:

```
badInds = numpy.where(valid == False)
```

This shows the error `E712 - comparison to False should be 'if cond is False:' or 'if not cond:'` which will break this statement.

**Comment by sigmavirus24** [comment] 2015-10-23 21:07
Strictly speaking there's no easy way for us to detect all of the cases where we might want to make an exception to E712. (Other cases involve ORMs, e.g., SQLAlchemy, SQLObject, etc.)

**Comment by tonkoandrew** [comment] 2016-03-27 03:55
This line can be written as:
`badInds = numpy.where(not bool(valid))`
or just
`badInds = numpy.where(not valid)`

**Comment by lzkelley** [comment] 2016-03-28 22:32
@tonkoandrew No.  Not a single one of those works...

```
In [154]: a = np.random.randint(0, 2, 10).astype(bool)
In [155]: a
Out[155]: array([ True, False, False,  True,  True, False,  True, False,  True,  True], dtype=bool)
In [156]: np.where(a is False)
Out[156]: (array([], dtype=int64),)
```

the `is` comparison does ***not*** work element-wise.

**Comment by tonkoandrew** [comment] 2016-03-29 05:09
`np.where(a.__eq__(False))`

**Comment by sigmavirus24** [comment] 2016-03-29 12:31
@tonkoandrew that's also a non-starter. There's no doubt that people should be allowed to use `==` in a case like this. It's something that works perfectly well, the problem is figuring out how to accommodate that.

Flake8 3.0 will allow for `# noqa: E712` on these lines, but before that is completed, there might be another way of solving this (sans rewriting the code to something far less elegant).

**Comment by cas--** [comment] 2018-05-10 10:02
For reference with `sqlalchemy` you can use [`is_` and `isnot`](http://docs.sqlalchemy.org/en/rel_1_0/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.is_) (perhaps similar in numpy?):

```diff
-            .filter(Group.addon == False)\
-            .filter(Group.product_id != None).all()  # noqa: E712
+            .filter(Group.addon.is_(False))\
+            .filter(Group.product_id.isnot(None)).all()
```
Source: https://stackoverflow.com/q/18998010/175584

**Comment by sigmavirus24** [comment] 2018-05-18 10:47
So Flake8 3.0 has been out for something longer than a year and allows for folks to do `# noqa: E712` on those lines. There's no good way to fix this in pycodestyle directly at this point. So, I'm closing this.

**Closed by sigmavirus24** 2018-05-18 10:47 UTC
