### ISSUE TITLE
"E226 missing whitespace around arithmetic operator" around high priority operator

### ISSUE THREAD

**Issue by hakonhagland** [PyCQA/pycodestyle#665] opened 2017-07-12 06:24 UTC
According to [PEP8](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements): 

> If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies)
>    x = x*2 - 1

I have this test program `t.py`: `y = x*x + 2`. When I run this under `flake8`:

```
$ flake8 --show-source --select=E226 t.py
.py:3:6: E226 missing whitespace around arithmetic operator
y = x*x + 2
     ^
```

I wonder why I get an `E226` here? It seems to be in conflict with the PEP8 guidelines?

**Comment by sigmavirus24** [comment] 2017-07-12 12:41
There's a few reasons:

1. Now that this tool is no longer called `pep8` we no longer feel required to implement the latest version of the living document since it's updated more frequently than people realize.

1. I believe that at the time `E226` was written, the current version of the document was yet a twinkle in someone's eye and the `Yes` and `No` examples as well as the text did not have the caveat for operators of different precedence.

1. If this has been noticed before (which I believe it has been but I haven't searched the old issues for this project yet) nobody has yet attempted to fix it. For me personally, I'm not concerned with it because I use parentheses for readability instead of spaces, thus for me it's not a priority. You're welcome to submit a pull request to fix this and we'll review it and include it, assuming it doesn't break other checks/existing okay code.

**Comment by asottile** [comment] 2020-02-19 20:47
Duplicate of #248

**Closed by asottile** 2020-02-19 20:47 UTC
