### ISSUE TITLE
Does it support  syntax := python 3.8?

### ISSUE THREAD

**Issue by func90** [PyCQA/pycodestyle#903] opened 2020-01-21 02:49 UTC
## Assignment expressions of Python 3.8
- when i use the syntax , it tells me ``missing whitespace after ':'pycodestyle(E231)``
![Snipaste_2020-01-21_10-47-57](https://user-images.githubusercontent.com/19530606/72771325-862c2b00-3c3b-11ea-9d88-12b24cd662ef.png)
- version of pycodestyle is  2.5.0

**Comment by asottile** [comment] 2020-01-21 02:54
duplicate of #865 (already fixed on master)

**Closed** 2020-01-21 14:57 UTC
