### ISSUE TITLE
W605 error while checking docstrings with regex inside it

### ISSUE THREAD

**Issue by smartfin** [PyCQA/pycodestyle#822] opened 2018-11-26 23:40 UTC
The bug is reproduced if you are using regex expression inside docstring with escaping of characters.

Here is example of code: 

```
import re


def test_regex_function():
    """
    Return compiled regex of which allows to process only specific file
    paths or extensions, e.g. r"^.*\.svg$".
    :return:
    """
    return re.compile(r"^.*\.svg$")
```

And result of running pycodestyle 2.4.0: 
```
pycodestyle 1.py   
                                                                                                                                                
1.py:9:-23: W605 invalid escape sequence '\.'
```

**Comment by FichteFoll** [comment] 2018-11-26 23:45
Duplicate of https://github.com/PyCQA/pycodestyle/issues/795 (and fixed in master).

**Comment by sigmavirus24** [comment] 2018-11-27 01:06
Well noticed @FichteFoll 

Duplicate of #795

**Closed by sigmavirus24** 2018-11-27 01:06 UTC
